# Build telecom_churn_100k dataset
- Build 100,000 rows CSV file from telecom_churn.csv that match the expresso_sample.csv user_ids

# Step 1 — Mount Google Drive

**Authorize access when prompted.**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Step 2 — Install & Import Libraries

In [ ]:
# pip install pandas
import pandas as pd

# Step 3 — Define File Paths

In [ ]:
# expresso_sample_file = "/path/to/expresso_sample.csv"
# telecom_churn_file = "/path/to/telecom_churn.csv"
# telecom_churn_100k_file = "/path/to/telecom_churn_100k.csv"

# Step 4 - Load datasets

In [ ]:
expresso_sample = pd.read_csv(expresso_sample_file)
telecom_churn = pd.read_csv(telecom_churn_file)

# Step 5 — Extract the exact 100,000 user_ids
- Assuming expresso_sample already contains 100,000 customers:

In [ ]:
sample_user_ids = expresso_sample["user_id"]
len(sample_user_ids)

100000

In [ ]:
expresso_sample.head()

,user_id,REGION,TENURE,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,MRG,REGULARITY,TOP_PACK,FREQ_TOP_PACK,CHURN
0,22322777e909ae0aa1c69e7b1fce40f333187fa6,DAKAR,K > 24 month,8650.0,37.0,8650.0,2883.0,38.0,2593.0,3.0,39.0,1.0,NaN,NaN,NO,59,"Data: 100 F=40MB,24H",20.0,0
1,453d2b534a53e30171b3c0c72dc7d56415619d8a,NaN,K > 24 month,1000.0,2.0,980.0,327.0,2.0,1362.0,NaN,1.0,9.0,NaN,NaN,NO,8,"Data:490F=1GB,7d",2.0,0
2,9e64b12fd171b51378111bbb1f25242e79c7be99,NaN,K > 24 month,NaN,NaN,NaN,NaN,NaN,1043.0,4.0,NaN,NaN,NaN,NaN,NO,8,NaN,NaN,1
3,369f886e40ef9ec4de23784888d412e5f336cca1,LOUGA,K > 24 month,250.0,1.0,250.0,83.0,2.0,389.0,5.0,NaN,NaN,NaN,NaN,NO,58,"Data: 200 F=100MB,24H",1.0,0
4,3524a53cd138dfe31a2f48c2cc21ed4129df1d10,DAKAR,K > 24 month,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NO,15,NaN,NaN,1

In [ ]:
expresso_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   user_id         100000 non-null  object
 1   REGION          60844 non-null   object
 2   TENURE          100000 non-null  object
 3   MONTANT         65059 non-null   float64
 4   FREQUENCE_RECH  65059 non-null   float64
 5   REVENUE         66484 non-null   float64
 6   ARPU_SEGMENT    66484 non-null   float64
 7   FREQUENCE       66484 non-null   float64
 8   DATA_VOLUME     50813 non-null   float64
 9   ON_NET          63663 non-null   float64
 10  ORANGE          58621 non-null   float64
 11  TIGO            40369 non-null   float64
 12  ZONE1           7909 non-null    float64
 13  ZONE2           6493 non-null    float64
 14  MRG             100000 non-null  object
 15  REGULARITY      100000 non-null  int64
 16  TOP_PACK        58264 non-null   object
 17  FREQ_TOP_PACK   58264 non-null   float64
 18  CHURN           100000 non-null  int64
dtypes: float64(12), int64(2), object(5)
memory usage: 14.5+ MB

# Step 6 - Filter telecom_churn to keep only those user_ids

In [ ]:
telecom_churn_100k = telecom_churn.set_index("user_id").loc[sample_user_ids].reset_index()

In [ ]:
telecom_churn_100k.head()

,user_id,region,tenure,montant,frequence_rech,revenue,arpu_segment,frequence,data_volume,on_net,...,region_coverage_index,region_signal_strength_index,region_network_quality_score,department_signal_strength_index,department_network_quality_score,department_coverage_index,arr_signal_strength_index,arr_network_quality_score,arr_coverage_index,churn
0,22322777e909ae0aa1c69e7b1fce40f333187fa6,DAKAR,K > 24 month,8650.0,37.0,8650.0,2883.0,38.0,2593.0,3.0,...,2386097.0,0.0,533.188255,0.0,134.914073,2386097.0,0.0,55.106100,2386097.0,0
1,453d2b534a53e30171b3c0c72dc7d56415619d8a,NaN,K > 24 month,1000.0,2.0,980.0,327.0,2.0,1362.0,NaN,...,4956.0,0.0,1.725000,0.0,1.050000,4956.0,0.0,1.050000,4956.0,0
2,9e64b12fd171b51378111bbb1f25242e79c7be99,NaN,K > 24 month,NaN,NaN,NaN,NaN,NaN,1043.0,4.0,...,4956.0,0.0,1.725000,0.0,1.050000,4956.0,0.0,1.050000,4956.0,1
3,369f886e40ef9ec4de23784888d412e5f336cca1,LOUGA,K > 24 month,250.0,1.0,250.0,83.0,2.0,389.0,5.0,...,399897.0,0.0,29.332979,0.0,10.543254,399897.0,0.0,4.315221,399897.0,0
4,3524a53cd138dfe31a2f48c2cc21ed4129df1d10,DAKAR,K > 24 month,NaN,NaN,NaN,NaN,NaN,NaN,7.0,...,2386097.0,0.0,533.188255,0.0,134.914073,2386097.0,0.0,55.106100,2386097.0,1

In [ ]:
telecom_churn_100k.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   user_id                           100000 non-null  object
 1   region                            60844 non-null   object
 2   tenure                            100000 non-null  object
 3   montant                           65059 non-null   float64
 4   frequence_rech                    65059 non-null   float64
 5   revenue                           66484 non-null   float64
 6   arpu_segment                      66484 non-null   float64
 7   frequence                         66484 non-null   float64
 8   data_volume                       50813 non-null   float64
 9   on_net                            63663 non-null   float64
 10  orange                            58621 non-null   float64
 11  tigo                              40369 non-null   float64
 12  zone1                             7909 non-null    float64
 13  zone2                             6493 non-null    float64
 14  mrg                               100000 non-null  object
 15  regularity                        100000 non-null  int64
 16  top_pack                          58264 non-null   object
 17  freq_top_pack                     58264 non-null   float64
 18  region_tower_count                91430 non-null   float64
 19  region_avg_range                  91430 non-null   float64
 20  region_avg_samples                91430 non-null   float64
 21  region_avg_signal                 91430 non-null   float64
 22  region_coverage_index             91430 non-null   float64
 23  region_signal_strength_index      91430 non-null   float64
 24  region_network_quality_score      91430 non-null   float64
 25  department_signal_strength_index  91430 non-null   float64
 26  department_network_quality_score  91430 non-null   float64
 27  department_coverage_index         91430 non-null   float64
 28  arr_signal_strength_index         91430 non-null   float64
 29  arr_network_quality_score         91430 non-null   float64
 30  arr_coverage_index                91430 non-null   float64
 31  churn                             100000 non-null  int64
dtypes: float64(25), int64(2), object(5)
memory usage: 24.4+ MB

# Step 7 - Verify alignment
- Shape: Ensures no rows were dropped or duplicated during the filter.
- Integrity: Ensures both sets contain the exact same unique IDs.
- Order: Ensures the sequence is identical from top to bottom.

In [ ]:
is_aligned = expresso_sample["user_id"].equals(telecom_churn_100k["user_id"])
print(f"Are the IDs of both datasets perfectly aligned? {is_aligned}")

Are the IDs of both datasets perfectly aligned? True

In [ ]:
# Check Head
verification_df = pd.DataFrame({
    'Expresso_IDs': expresso_sample["user_id"].values,
    'Telecom_IDs': telecom_churn_100k["user_id"].values
})

print(verification_df.head())

                               Expresso_IDs  \
0  22322777e909ae0aa1c69e7b1fce40f333187fa6
1  453d2b534a53e30171b3c0c72dc7d56415619d8a
2  9e64b12fd171b51378111bbb1f25242e79c7be99
3  369f886e40ef9ec4de23784888d412e5f336cca1
4  3524a53cd138dfe31a2f48c2cc21ed4129df1d10

                                Telecom_IDs
0  22322777e909ae0aa1c69e7b1fce40f333187fa6
1  453d2b534a53e30171b3c0c72dc7d56415619d8a
2  9e64b12fd171b51378111bbb1f25242e79c7be99
3  369f886e40ef9ec4de23784888d412e5f336cca1
4  3524a53cd138dfe31a2f48c2cc21ed4129df1d10

In [ ]:
# Check shape
len(expresso_sample) == len(telecom_churn_100k)

True

In [ ]:
# Check Integrity
set(expresso_sample["user_id"]) == set(telecom_churn_100k["user_id"])

True

In [ ]:
# Chek Order
(expresso_sample["user_id"].values == telecom_churn_100k["user_id"].values).all()

np.True_

# Step 8 - Save the final dataset

In [ ]:
telecom_churn_100k.to_csv(telecom_churn_100k_file, index=False)